COUNT: 1
SEC_GROUP:
 - sg-19b53c7e
 - sg-a46b1ac3
AMI: non-secure 
TYPE: t2.medium
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-8cf149e8  
TAGS: {Class: "mq-sb", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: sb 
PUBLIC_IP: no
PRIV_IP: no
IAM_ROLE: s3_readonly_role
ZONE: glp
EC2_VOLUME_SIZE: 8
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: true
