COUNT: 1
SEC_GROUP: sg-29081645 
AMI: non-secure 
TYPE: m3.medium
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-808127e4 
TAGS: {Class: "mq-test", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: test 
PUBLIC_IP: no
PRIV_IP: 172.16.30.30
IAM_ROLE: s3_readonly_role
ZONE: glp
EC2_VOLUME_SIZE: 8
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: true

 
