# role to set up EPEL repo
# to be expanded to include CentOS5
---
 - name: Install EPEL repo
   yum:
     name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
     state=installed
   when: 
