COUNT: 1
SEC_GROUP: sg-29081645 
AMI: non-secure 
TYPE: m3.medium 
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-808127e4 
TAGS: {Class: "mysql-test", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: test 
ZONE: glp
PUBLIC_IP: no
PRIV_IP: 172.16.30.15
IAM_ROLE: s3_readonly_role
EC2_ROOT_VOLUME_SIZE: 8
EC2_LVM_VOLUME_SIZE: 25 
LVM_PV_DEVICE_LIST: /dev/xvdb
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_ROOT_VOLUME_SIZE }}"
   delete_on_termination: true
 - device_name: /dev/xvdb
   volume_size: "{{ EC2_LVM_VOLUME_SIZE }}"
   delete_on_termination: true

 
