COUNT: 1
SEC_GROUP:
  - sg-19b53c7e 
  - sg-1360f974
  - sg-97c7abf0
AMI: non-secure 
TYPE: t2.micro 
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-dff149bb
TAGS: {Class: "lb-sb", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: sb
ZONE: glp
PUBLIC_IP: no
PRIV_IP: no
ELIP: yes
IAM_ROLE: no
EC2_VOLUME_SIZE: 8
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: true

 
