COUNT: 1
SEC_GROUP: 
 - sg-19b53c7e
 - sg-99f483fe
AMI: non-secure 
TYPE: t2.large
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-8cf149e8
TAGS: {Class: "mysql-sb", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: sb 
ZONE: glp
PUBLIC_IP: no
#PRIV_IP: 172.17.9.69
PRIV_IP: no
IAM_ROLE: s3_readonly_role
EC2_ROOT_VOLUME_SIZE: 8
EC2_LVM_VOLUME_SIZE: 25
LVM_PV_DEVICE_LIST: /dev/xvdb
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_ROOT_VOLUME_SIZE }}"
   delete_on_termination: true
 - device_name: /dev/xvdb
   volume_size: "{{ EC2_LVM_VOLUME_SIZE }}"
   delete_on_termination: true

 
