COUNT: 1
SEC_GROUP:
 - sg-1afc807d
 - sg-b1ea96d6
AMI: non-secure 
TYPE: t2.small
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-4f26be2b 
TAGS: {Class: "corp-web-prod", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: prod
ZONE: glp
PUBLIC_IP: no
PRIV_IP: no
ELIP: yes
IAM_ROLE: s3_readonly_role
EC2_VOLUME_SIZE: 8
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: true

 
