# Role to install Jenkins. Will install the latest version
#
# Relies on having Apache installed using the apache role
#
---
 - name: Add jenkins-slave user
   user:
     name: jenkins-slave
     group: admin
     home: /jenkins-slave
     createhome: yes

 - name: Set users authorized_key
   authorized_key:
     user: jenkins-slave
     exclusive: yes
     key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFOcz0o0hFW8b3GMCanweNtfSAuR9Kd11ljvS0G+MvOdGJ0xabz4XzKpQ+mGXInLt+vZNHV3UQE6FlKyzgjRnVbRJO+tZo8piifw0t/3IHaGIUmPubCYRUSO/xLTXq+ay6zzLHLcP4fDNYEDUFQbWYj9DPhdOezI6sVrzdykCcKjmyh0W9QLzZ5KEMjdD2+UqklqY6RN+F5Vmifq0IlGTnfA/muziEYORCSr071/FJMjL3h8IOiPOfaQdR6vTLf/Ludh9isml97kcgaIb2swrP+5o6Vcp9Vd/VrwxnumbEaxpmzYOo2oQNcktHjz15ohFzNtGmL6VAEyBzkN57Nq9Z jenkins-slave
     state: present  


 - name: Fetch Jenkins repo details
   get_url:
     url=http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
     dest=/etc/yum.repos.d/jenkins.repo

 - name: Install Jenkins repo key
   rpm_key:
     key=http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
     state=present 

 - name: Install jenkins
   yum:
     name={{ item }}
     state=present
   with_items:
    - xorg-x11-server-Xvfb.x86_64
    
# - name: Start and Enable Jenkins
#   service:
#     name=jenkins
#     state=started
#     enabled=yes

# - name: Upload jenkins Apache conf
#   template:
#     src=jenkins.conf.j2
#     dest=/etc/httpd/conf.d/jenkins.conf
#   notify:
#    - Restart httpd
