COUNT: 1
SEC_GROUP: sg-2750a840  
AMI: non-secure 
TYPE: t2.small
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-f6f72392
TAGS: {Class: "openvpn-server", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: prod
PUBLIC_IP: no
ELIP: yes
PRIV_IP: 172.18.1.4
EC2_VOLUME_SIZE: 8
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: true

 
