COUNT: 1
SEC_GROUP: 
 - euw-prod-base
 - euw-prod-http
 - euw-prod-corosync
AMI: non-secure 
TYPE: m4.xlarge
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-b667f7d3
TAGS: {Class: "search-cache-prod", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: prod
ZONE: glp
PUBLIC_IP: no
PRIV_IP: no
IAM_ROLE: s3_readonly_role
EC2_VOLUME_SIZE: 20
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: true
VIP: 172.20.14.100 
