# Role to disable SELinux
#
#
---
 - name: Set SELinux to disabled
   selinux:
     state=disabled
   register: selinux

 - name: Restart to disable SELinux
   command: shutdown -r now "Ansible updates triggered"
   when: selinux.changed and (packer is not defined)

 - name: Wait for reboot
   local_action: wait_for port=22 host="{{ ansible_default_ipv4.address }}" delay=10 timeout=320 state=started
   become: no
   when: selinux.changed and (packer is not defined)
