---
- hosts: jenkins
  remote_user: ec2-user
  vars:
#    - java_download_url: http://download.oracle.com/otn-pub/java/jdk/8u73-b02/jdk-8u73-linux-x64.rpm
    - java_download_url: http://download.oracle.com/otn/java/jdk/7u71-b14/jdk-7u71-linux-x64.rpm
    - download_dir: /tmp
    - java_package: "{{download_dir}}/jdk-7u71-linux-x64.rpm"
#    - java_package: "{{download_dir}}/jdk-8u73-linux-x64.rpm"
  tasks:
    - name: create LVM volume group
      lvg: vg=jenkins_vg pvs=/dev/xvdb pesize=4
      sudo: True

    - name: create LVM
      lvol: vg=jenkins_vg lv=store size=299g
      sudo: True

    - name: create filesystem
      filesystem: fstype=ext4 dev=/dev/jenkins_vg/store
      sudo: True

    - name: create /jenkins directory
      file: path=/jenkins state=directory
      sudo: True

    - name: mount LVM and add to fstab
      mount: name=/jenkins src=/dev/jenkins_vg/store fstype=ext4 state=present
      sudo: True

    - name: install wget
      yum: name=wget state=latest
      sudo: True

    - name: download java
      command: "wget -q -O {{java_package}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{java_download_url}} creates={{java_package}}"
      sudo: True

    - name: install Oracle JDK
      yum: name="{{java_package}}" state=present
      sudo: True

    - name: create jenkins symlink to lvm
      file: src=/jenkins dest=/var/lib/jenkins state=link
      sudo: True

    - name: download jenkins repo file
      get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo
      sudo: True

    - name: import jenkins repo key
      rpm_key: state=present key=http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
      sudo: True

    - name: install jenkins
      yum: name=jenkins state=present 
      sudo: True

    - name: Change ownership of jenkins folder to the jenkins user and jenkins group
      file: path=/jenkins owner=jenkins group=jenkins recurse=yes
      sudo: True

    - name: start jenkins
      service: name=jenkins enabled=yes state=started
      sudo: True

    - name: download maven
      get_url: url=http://apache.mirror.anlx.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz dest=/tmp/apache-maven-3.3.9-bin.tar.gz
      sudo: True

    - name: unpack maven
      unarchive: "copy=no src=/tmp/apache-maven-3.3.9-bin.tar.gz dest=/opt creates=/opt/apache-maven-3.3.9"
      sudo: True
 
    - name: create maven symlink
      file: src=/opt/apache-maven-3.3.9 dest=/opt/maven state=link
      sudo: True

    - name: add maven to path
      command: alternatives --install /usr/bin/mvn mvn /opt/apache-maven-3.3.9/bin/mvn 1
      sudo: True

    - name: copy maven settings.xml
      copy: src=/etc/ansible/settings.xml dest=/opt/apache-maven-3.3.9/conf/settings.xml
      sudo: True

#  - name: ensure iptables is configured to allow ssh traffic (port 8080/tcp)
#    lineinfile:
#      dest=/etc/sysconfig/iptables 
#      state=present 
#      regexp="^.*INPUT.*tcp.*8080.*ACCEPT" 
#      insertafter="^.*INPUT.*ESTABLISHED,RELATED.*ACCEPT" line="-A INPUT -m state --state NEW -m tcp -p tcp --dport 8080 -j ACCEPT" 
#      backup=yes
#
#  - name: ensure forwarding 80 to jenkins
#    lineinfile:
#      dest=/etc/sysconfig/iptables
#      state=present
#      regexp="^.*PREROUTING.*tcp.*8080"
#      insertbefore="BOF" line="*nat\n:PREROUTING ACCEPT [0:0]\n:OUTPUT ACCEPT [0:0]\n:POSTROUTING ACCEPT [0:0]\n-A PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to-destination :8080\nCOMMIT"
#      backup=yes
#
#  - name: open firewall for jenkins
#    command: /sbin/iptables -I INPUT 1 -p tcp --dport 8080 -j ACCEPT -m comment --comment "Jenkins"
#
#  - name: Allow port 80
#    command: >
#      iptables -A INPUT -p tcp -m tcp --dport 8080
#      -m comment --comment "Allow Jenkins" -j ACCEPT
#
#  - name: save iptables
#    command: iptables-save
#    iptables: chain=INPUT in_interface=eth0 protocol=tcp destination_port=8080 jump=ACCEPT comment="Jenkins Traffic 8080"
#    become: yes
#
#  - name: redirect http to jenkins
#    iptables: table=nat chain=PREROUTING in_interface=eth0 protocol=tcp match=tcp destination_port=80 jump=REDIRECT to_ports=8080 comment="Jenkins Traffic to 8080"
#    become: yes
#    notify:
#    - restart iptables
#
#  handlers:
#  - name: restart iptables
#    service: name=iptables state=restarted
