COUNT: 1
SEC_GROUP: 
 - euw-test-base
 - euw-test-http
 - euw-test-corosync
AMI: non-secure 
TYPE: t2.large 
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-8cf149e8
TAGS: {Class: "cache-sb", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: sb 
ZONE: glp
PUBLIC_IP: no
PRIV_IP: no
IAM_ROLE: s3_readonly_role
EC2_VOLUME_SIZE: 8
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: true
VIP: 172.17.9.100
