COUNT: 1
SEC_GROUP: 
 - "{{ ENV }}-{{ REGION }}-base"
 - "{{ ENV }}-{{ REGION }}-dmz-corosync"
AMI: non-secure
TYPE: t2.small 
BUILD_KEY: buildscm.pem
TAGS: {Class: "gw-sb", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: sb 
ZONE: glp
PUBLIC_IP: no
PRIV_IP: no
ELIP: yes
IAM_ROLE: s3_readonly_role
REGION: eu-west-1
EC2_VOLUME_SIZE: 8
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: true
ELASTIC_IP: 52.213.72.242
ELASTIC_IP_ALLOC: eipalloc-41cee925
