COUNT: 1
SEC_GROUP:
 - sg-1afc807d
 - sg-44fd8123
 - sg-b1ea96d6
 - sg-f12a6496
AMI: non-secure 
TYPE: t2.micro
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-5a5f823e 
TAGS: {Class: "jenkins-admin", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: prod
PUBLIC_IP: no
PRIV_IP: 172.18.2.5
ZONE: glp
IAM_ROLE: s3_readonly_role
EC2_VOLUME_SIZE: 8
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: true
