COUNT: 1
SEC_GROUP:
 - sg-1afc807d
 - sg-ed5ff58b 
AMI: non-secure 
TYPE: t2.large
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-5a5f823e 
TAGS: {Class: "openvas", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: prod
PUBLIC_IP: no
ZONE: glp
IAM_ROLE: s3_readonly_role
EC2_VOLUME_SIZE: 20
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: true
