COUNT: 1
SEC_GROUP: 
 - sg-9d8e88fa 
AMI: non-secure 
TYPE: t2.small 
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-5d69f938
TAGS: {Class: "hc-dt", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: prod
ZONE: glp
PUBLIC_IP: no
PRIV_IP: no 
IAM_ROLE: s3_readonly_role 
EC2_VOLUME_SIZE: 8 
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: false 
 - device_name: /dev/sdb
   volume_size: 25
   delete_on_termination: false
   encrypted: true
aws_mounts:
  - source: /dev/xvdb
    destination: /data/collins/
    fstype: ext4 
