COUNT: 1
SEC_GROUP: 
 - sg-19b53c7e
 - sg-79e0d41e
 - sg-1360f974
AMI: non-secure 
TYPE: t2.small
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-8cf149e8 
TAGS: {Class: "corosync-sb", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: sb
ZONE: glp
PUBLIC_IP: no
IAM_ROLE: s3_readonly_role
EC2_VOLUME_SIZE: 8
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: true
 - device_name: /dev/xvdb
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: true
DRBD_SECRET: "Icthf4M!SFsK#|CSx=ia"
VIP: 172.17.9.75
