# Role to configure varnish for IP based failover
#
# Depends on:
# - corosync
---
 - name: Get ENI Facts
   ec2_eni_facts:
     region: eu-west-1
     filters:
       private-ip-address: "{{ ansible_default_ipv4.address }}"
   delegate_to: localhost
   become: no
   register: eni

 - name: Attach secondary IP to primary server ENI
   ec2_eni:
     subnet_id: "{{ eni.network_interfaces.0.subnet_id }}"
     eni_id: "{{ eni.network_interfaces.0.network_interface_id }}"
     region: eu-west-1
     secondary_private_ip_addresses: "{{ VIP }}"
   delegate_to: localhost
   become: no
   when: "'01' in inventory_hostname"

 - name: Create DNS record for VIP
   route53 :
     command: create
     zone: "{{ ENV }}.{{ ZONE }}"
     record: "search-cache-vip.{{ ENV }}.{{ ZONE }}"
     type: A
     ttl: 60
     value: "{{ VIP }}"
     overwrite: yes
     private_zone: yes
     retry_interval: 10
   delegate_to: localhost
   become: no
   when: "'01' in inventory_hostname"

 - name: Start corosync
   service:
     name=corosync
     state=started
     enabled=yes

 - name: Pause to allow corosync to start
   pause: 
     seconds=20

 - name: Make ec2 resource dir
   file:
     path=/usr/lib/ocf/resource.d/ec2/
     state=directory

 - name: Upload EC2 VIP script
   template:
     src=virtual-ip.j2
     dest=/usr/lib/ocf/resource.d/ec2/virtual-ip
     mode=u+x

 - name: Set Standard settings for corosync
   shell: "{{ item }}"
   with_items:
    - "crm configure property no-quorum-policy=ignore"
    - "crm configure property stonith-enabled=false"
   when: "'01' in inventory_hostname"

 - name: Enable required Services
   command: "{{ item }}"
   with_items:
    - "crm configure primitive virtual-ip ocf:ec2:virtual-ip op monitor timeout=90 interval=90 on-fail=restart failure-timeout=60s op start timeout=40s interval=0 op stop timeout=60s interval=0 meta is-managed=true resource-stickiness=100 failure-timeout=90 target-role=Started migration-threshold=3"
   when: "'01' in inventory_hostname"
