COUNT: 1
SEC_GROUP:
  - sg-089d2f6f 
  - sg-5d82303a
  - sg-87b1d4e0
AMI: non-secure 
TYPE: t2.micro 
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-d6b966b3
TAGS: {Class: "ns-test", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: test 
ZONE: glp
PUBLIC_IP: no
ELIP: yes
IAM_ROLE: no
EC2_VOLUME_SIZE: 8
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: true

 
