LISTENERS:
 - protocol: http
   load_balancer_port: 80
   instance_port: 21701
   proxy_protocol: True
HEALTH_CHECK:
  ping_protocol: http
  ping_port: 21701
  ping_path: "/swagger"
  response_timeout: 5
  interval: 10
  unhealthy_threshold: 2
  healthy_threshold: 5
ELB_NAME: promo-app-test 
