COUNT: 1
SEC_GROUP:
 - sg-1afc807d
 - sg-fc000d9b
 - sg-b1ea96d6 
AMI: non-secure 
TYPE: c4.large
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-5a5f823e 
TAGS: {Class: "zabbix-server", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: prod
IAM_ROLE: no
PUBLIC_IP: no
PRIV_IP: 172.18.2.4
ZONE: glp
EC2_VOLUME_SIZE: 20
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: true
