ZONE: glp
COUNT: 1
SEC_GROUP: sg-b45749d8 
AMI: non-secure 
TYPE: t2.micro
BUILD_KEY: buildscm.pem
VPC_SUBNET: subnet-56f2d421
TAGS: {Class: "prod-{{ FUNC }}-server", Name: "{{ inventory_hostname }}", Env: "{{ ENV }}"}
ENV: prod
PUBLIC_IP: no
ELIP: yes
EC2_VOLUME_SIZE: 10
VOLUMES:
 - device_name: /dev/sda1
   volume_size: "{{ EC2_VOLUME_SIZE }}"
   delete_on_termination: true
